<a href="https://colab.research.google.com/github/AlisterVento/PI-01.MLOps/blob/main/user_items_Analisis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd #Cargaremos pandas para manejar los datos",
import numpy as np #Cargaremos numpy para manejar los datos,
import json as json  #Cargaremos json para manejar los datos",
import gzip #Cargaremos gzip para manejar los datos,
import ast
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
url03=r'/content/drive/MyDrive/2023/Henry/MLOps Henry/Datos/users_items.json.gz'

In [ ]:
filas=[]
with gzip.open(url03) as file:
    for line in file.readlines():
        line = line.decode('utf-8')
        filas.append(ast.literal_eval(line))

df_user_items = pd.DataFrame(filas)
df_user_items.head()

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,328,76561197963445855,http://steamcommunity.com/id/Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea..."

In [ ]:
def check_df(dataset, head = 5):
    """
    Funcion creada para tener una vista general de la base de datos
    """
    print('*'*30 + 'Forma de la base de datos' + '*'*30, end = '\n'*2)
    print(dataset.shape, end = '\n'*2)#Tamaño de la base de datos

    print('*'*30 + 'Informacion general de la base de datos' + '*'*30, end = '\n'*2)
    print(dataset.info(), end = '\n'*2)# Informacion general

    print('*'*30 + 'NaN cantidad de nulos' + '*'*30, end = '\n'*2)
    print(dataset.isnull().sum(), end = '\n'*2)#Cuenta la cantidad de NaN por columna

In [ ]:
check_df(df_user_items)

******************************Forma de la base de datos******************************

(88310, 5)

******************************Informacion general de la base de datos******************************

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88310 entries, 0 to 88309
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      88310 non-null  object
 1   items_count  88310 non-null  int64
 2   steam_id     88310 non-null  object
 3   user_url     88310 non-null  object
 4   items        88310 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.4+ MB
None

******************************NaN cantidad de nulos******************************

user_id        0
items_count    0
steam_id       0
user_url       0
items          0
dtype: int64

In [ ]:
df_user_items2=df_user_items.explode('items')

In [ ]:
df_user_items2

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '10', 'item_name': 'Counter-Strike..."
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '20', 'item_name': 'Team Fortress ..."
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '30', 'item_name': 'Day of Defeat'..."
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '40', 'item_name': 'Deathmatch Cla..."
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '50', 'item_name': 'Half-Life: Opp..."
...,...,...,...,...,...
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"{'item_id': '373330', 'item_name': 'All Is Dus..."
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"{'item_id': '388490', 'item_name': 'One Way To..."
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"{'item_id': '521570', 'item_name': 'You Have 1..."
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"{'item_id': '519140', 'item_name': 'Minds Eyes..."
88309,edward_tremethick,0,76561198331598578,http://steamcommunity.com/id/edward_tremethick,NaN

In [ ]:
df_user_items2.isnull().sum()

user_id            0
items_count        0
steam_id           0
user_url           0
items          16806
dtype: int64

In [ ]:
df_user_items2[df_user_items2['items'].isnull()]

,user_id,items_count,steam_id,user_url,items
9,Wackky,0,76561198039117046,http://steamcommunity.com/id/Wackky,NaN
11,76561198079601835,0,76561198079601835,http://steamcommunity.com/profiles/76561198079...,NaN
31,hellom8o,0,76561198117222320,http://steamcommunity.com/id/hellom8o,NaN
38,starkillershadow553,0,76561198059648579,http://steamcommunity.com/id/starkillershadow553,NaN
54,darkenkane,0,76561198058876001,http://steamcommunity.com/id/darkenkane,NaN
...,...,...,...,...,...
88298,76561198316380182,0,76561198316380182,http://steamcommunity.com/profiles/76561198316...,NaN
88299,76561198316970597,0,76561198316970597,http://steamcommunity.com/profiles/76561198316...,NaN
88300,76561198318100691,0,76561198318100691,http://steamcommunity.com/profiles/76561198318...,NaN
88307,XxLaughingJackClown77xX,0,76561198328759259,http://steamcommunity.com/id/XxLaughingJackClo...,NaN
88309,edward_tremethick,0,76561198331598578,http://steamcommunity.com/id/edward_tremethick,NaN

In [ ]:
df_user_items2.dropna(subset=['items'],inplace=True)

In [ ]:
df_user_items2

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '10', 'item_name': 'Counter-Strike..."
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '20', 'item_name': 'Team Fortress ..."
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '30', 'item_name': 'Day of Defeat'..."
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '40', 'item_name': 'Deathmatch Cla..."
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '50', 'item_name': 'Half-Life: Opp..."
...,...,...,...,...,...
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"{'item_id': '346330', 'item_name': 'BrainBread..."
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"{'item_id': '373330', 'item_name': 'All Is Dus..."
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"{'item_id': '388490', 'item_name': 'One Way To..."
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"{'item_id': '521570', 'item_name': 'You Have 1..."
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"{'item_id': '519140', 'item_name': 'Minds Eyes..."

In [ ]:
df_user_items2

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '10', 'item_name': 'Counter-Strike..."
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '20', 'item_name': 'Team Fortress ..."
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '30', 'item_name': 'Day of Defeat'..."
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '40', 'item_name': 'Deathmatch Cla..."
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"{'item_id': '50', 'item_name': 'Half-Life: Opp..."
...,...,...,...,...,...
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"{'item_id': '346330', 'item_name': 'BrainBread..."
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"{'item_id': '373330', 'item_name': 'All Is Dus..."
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"{'item_id': '388490', 'item_name': 'One Way To..."
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"{'item_id': '521570', 'item_name': 'You Have 1..."
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"{'item_id': '519140', 'item_name': 'Minds Eyes..."

In [ ]:
for elemento,diccionario in df_user_items2['items'].head().items():
    df=pd.DataFrame(columns=diccionario.keys())
df

Empty DataFrame
Columns: [item_id, item_name, playtime_forever, playtime_2weeks]
Index: []

In [ ]:
new_rows = []

# Iterate over the dictionaries in the 'reviews' column
for elemento, diccionario in df_user_items2['items'].items():
    new_row = pd.DataFrame(diccionario, index=[elemento])  # Create a new row DataFrame
    new_rows.append(new_row)  # Append the new row to the list

# Concatenate the list of new rows with the original DataFrame
result_df = pd.concat([df, *new_rows])

In [ ]:
# Reset index
df_user_items3=df_user_items2.join(result_df)

In [ ]:
df_user_items3.drop_duplicates(subset=['user_id','item_name'],inplace=True)

El notebook fue trabajado en un jupyter notebook de manera offline sin embargo el resultado no se pudo volver a generar y visualizar  debido a la alta demanda computacional y memoria, sin embargo el resultado se pudo guardar en un archivo **parquet** el cual lo usaremos cargaremos desde google drive

In [ ]:
url05=r'/content/drive/MyDrive/2023/Henry/MLOps Henry/Datos/users_items_data_fextract.parquet.gzip'

In [ ]:
result_df=pd.read_parquet(url05)

In [ ]:
result_df

,user_id,items_count,steam_id,user_url,items.item_id,items.item_name,items.playtime_2weeks,items.playtime_forever
index,,,,,,,,
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,10,Counter-Strike,0,6
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,20,Team Fortress Classic,0,0
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,30,Day of Defeat,0,7
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,40,Deathmatch Classic,0,0
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,50,Half-Life: Opposing Force,0,0
...,...,...,...,...,...,...,...,...
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,346330,BrainBread 2,0,0
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,373330,All Is Dust,0,0
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,388490,One Way To Die: Steam Edition,3,3
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,521570,You Have 10 Seconds 2,4,4
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,519140,Minds Eyes,3,3

# Sección nueva